apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: ikol-smailandstuff
spec:
  build:
    secrets:
      - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "44af0562-7c70-42e3-a9c3-bff788dc86d0"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET